// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kondo97/mattermost-plugin-rtk/server/rtkclient (interfaces: RTKClient)
//
// Generated by this command:
//
//	mockgen -destination=server/rtkclient/mocks/mock_rtkclient.go -package=mocks github.com/kondo97/mattermost-plugin-rtk/server/rtkclient RTKClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	rtkclient "github.com/kondo97/mattermost-plugin-rtk/server/rtkclient"
	gomock "go.uber.org/mock/gomock"
)

// MockRTKClient is a mock of RTKClient interface.
type MockRTKClient struct {
	ctrl     *gomock.Controller
	recorder *MockRTKClientMockRecorder
	isgomock struct{}
}

// MockRTKClientMockRecorder is the mock recorder for MockRTKClient.
type MockRTKClientMockRecorder struct {
	mock *MockRTKClient
}

// NewMockRTKClient creates a new mock instance.
func NewMockRTKClient(ctrl *gomock.Controller) *MockRTKClient {
	mock := &MockRTKClient{ctrl: ctrl}
	mock.recorder = &MockRTKClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRTKClient) EXPECT() *MockRTKClientMockRecorder {
	return m.recorder
}

// CreateMeeting mocks base method.
func (m *MockRTKClient) CreateMeeting() (*rtkclient.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeeting")
	ret0, _ := ret[0].(*rtkclient.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeeting indicates an expected call of CreateMeeting.
func (mr *MockRTKClientMockRecorder) CreateMeeting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeeting", reflect.TypeOf((*MockRTKClient)(nil).CreateMeeting))
}

// DeleteWebhook mocks base method.
func (m *MockRTKClient) DeleteWebhook(webhookID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhook", webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebhook indicates an expected call of DeleteWebhook.
func (mr *MockRTKClientMockRecorder) DeleteWebhook(webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhook", reflect.TypeOf((*MockRTKClient)(nil).DeleteWebhook), webhookID)
}

// EndMeeting mocks base method.
func (m *MockRTKClient) EndMeeting(meetingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndMeeting", meetingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndMeeting indicates an expected call of EndMeeting.
func (mr *MockRTKClientMockRecorder) EndMeeting(meetingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndMeeting", reflect.TypeOf((*MockRTKClient)(nil).EndMeeting), meetingID)
}

// RegisterWebhook mocks base method.
func (m *MockRTKClient) RegisterWebhook(url string, events []string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterWebhook", url, events)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RegisterWebhook indicates an expected call of RegisterWebhook.
func (mr *MockRTKClientMockRecorder) RegisterWebhook(url, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterWebhook", reflect.TypeOf((*MockRTKClient)(nil).RegisterWebhook), url, events)
}

// GenerateToken mocks base method.
func (m *MockRTKClient) GenerateToken(meetingID, userID, displayName, preset string) (*rtkclient.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", meetingID, userID, displayName, preset)
	ret0, _ := ret[0].(*rtkclient.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockRTKClientMockRecorder) GenerateToken(meetingID, userID, displayName, preset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockRTKClient)(nil).GenerateToken), meetingID, userID, displayName, preset)
}
