// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kondo97/mattermost-plugin-rtk/server/push (interfaces: PushSender)
//
// Generated by this command:
//
//	mockgen -destination=server/push/mocks/mock_push.go -package=mocks github.com/kondo97/mattermost-plugin-rtk/server/push PushSender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	kvstore "github.com/kondo97/mattermost-plugin-rtk/server/store/kvstore"
	gomock "go.uber.org/mock/gomock"
)

// MockPushSender is a mock of PushSender interface.
type MockPushSender struct {
	ctrl     *gomock.Controller
	recorder *MockPushSenderMockRecorder
	isgomock struct{}
}

// MockPushSenderMockRecorder is the mock recorder for MockPushSender.
type MockPushSenderMockRecorder struct {
	mock *MockPushSender
}

// NewMockPushSender creates a new mock instance.
func NewMockPushSender(ctrl *gomock.Controller) *MockPushSender {
	mock := &MockPushSender{ctrl: ctrl}
	mock.recorder = &MockPushSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSender) EXPECT() *MockPushSenderMockRecorder {
	return m.recorder
}

// SendCallEnded mocks base method.
func (m *MockPushSender) SendCallEnded(session *kvstore.CallSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCallEnded", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCallEnded indicates an expected call of SendCallEnded.
func (mr *MockPushSenderMockRecorder) SendCallEnded(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCallEnded", reflect.TypeOf((*MockPushSender)(nil).SendCallEnded), session)
}

// SendIncomingCall mocks base method.
func (m *MockPushSender) SendIncomingCall(session *kvstore.CallSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendIncomingCall", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendIncomingCall indicates an expected call of SendIncomingCall.
func (mr *MockPushSenderMockRecorder) SendIncomingCall(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendIncomingCall", reflect.TypeOf((*MockPushSender)(nil).SendIncomingCall), session)
}
