// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kondo97/mattermost-plugin-rtk/server/store (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=server/store/mocks/mock_store.go -package=mocks github.com/kondo97/mattermost-plugin-rtk/server/store Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	store "github.com/kondo97/mattermost-plugin-rtk/server/store"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddCallParticipant mocks base method.
func (m *MockStore) AddCallParticipant(callID, userID string) ([]string, bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCallParticipant", callID, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// AddCallParticipant indicates an expected call of AddCallParticipant.
func (mr *MockStoreMockRecorder) AddCallParticipant(callID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCallParticipant", reflect.TypeOf((*MockStore)(nil).AddCallParticipant), callID, userID)
}

// ClearWebhookConfig mocks base method.
func (m *MockStore) ClearWebhookConfig(appConfigID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearWebhookConfig", appConfigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearWebhookConfig indicates an expected call of ClearWebhookConfig.
func (mr *MockStoreMockRecorder) ClearWebhookConfig(appConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearWebhookConfig", reflect.TypeOf((*MockStore)(nil).ClearWebhookConfig), appConfigID)
}

// CreateCallSession mocks base method.
func (m *MockStore) CreateCallSession(session *store.CallSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCallSession", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCallSession indicates an expected call of CreateCallSession.
func (mr *MockStoreMockRecorder) CreateCallSession(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCallSession", reflect.TypeOf((*MockStore)(nil).CreateCallSession), session)
}

// EndCall mocks base method.
func (m *MockStore) EndCall(callID string, endAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndCall", callID, endAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndCall indicates an expected call of EndCall.
func (mr *MockStoreMockRecorder) EndCall(callID, endAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndCall", reflect.TypeOf((*MockStore)(nil).EndCall), callID, endAt)
}

// GetActiveAppConfigID mocks base method.
func (m *MockStore) GetActiveAppConfigID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAppConfigID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAppConfigID indicates an expected call of GetActiveAppConfigID.
func (mr *MockStoreMockRecorder) GetActiveAppConfigID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAppConfigID", reflect.TypeOf((*MockStore)(nil).GetActiveAppConfigID))
}

// GetAllActiveCalls mocks base method.
func (m *MockStore) GetAllActiveCalls() ([]*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveCalls")
	ret0, _ := ret[0].([]*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveCalls indicates an expected call of GetAllActiveCalls.
func (mr *MockStoreMockRecorder) GetAllActiveCalls() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveCalls", reflect.TypeOf((*MockStore)(nil).GetAllActiveCalls))
}

// GetAllCallsChannels mocks base method.
func (m *MockStore) GetAllCallsChannels() ([]*store.CallsChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCallsChannels")
	ret0, _ := ret[0].([]*store.CallsChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCallsChannels indicates an expected call of GetAllCallsChannels.
func (mr *MockStoreMockRecorder) GetAllCallsChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCallsChannels", reflect.TypeOf((*MockStore)(nil).GetAllCallsChannels))
}

// GetAppID mocks base method.
func (m *MockStore) GetAppID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppID indicates an expected call of GetAppID.
func (mr *MockStoreMockRecorder) GetAppID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppID", reflect.TypeOf((*MockStore)(nil).GetAppID))
}

// GetCallByChannel mocks base method.
func (m *MockStore) GetCallByChannel(channelID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByChannel", channelID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByChannel indicates an expected call of GetCallByChannel.
func (mr *MockStoreMockRecorder) GetCallByChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByChannel", reflect.TypeOf((*MockStore)(nil).GetCallByChannel), channelID)
}

// GetCallByID mocks base method.
func (m *MockStore) GetCallByID(callID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByID", callID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByID indicates an expected call of GetCallByID.
func (mr *MockStoreMockRecorder) GetCallByID(callID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByID", reflect.TypeOf((*MockStore)(nil).GetCallByID), callID)
}

// GetCallByMeetingID mocks base method.
func (m *MockStore) GetCallByMeetingID(meetingID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByMeetingID", meetingID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByMeetingID indicates an expected call of GetCallByMeetingID.
func (mr *MockStoreMockRecorder) GetCallByMeetingID(meetingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByMeetingID", reflect.TypeOf((*MockStore)(nil).GetCallByMeetingID), meetingID)
}

// GetCallsChannel mocks base method.
func (m *MockStore) GetCallsChannel(channelID string) (*store.CallsChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallsChannel", channelID)
	ret0, _ := ret[0].(*store.CallsChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallsChannel indicates an expected call of GetCallsChannel.
func (mr *MockStoreMockRecorder) GetCallsChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallsChannel", reflect.TypeOf((*MockStore)(nil).GetCallsChannel), channelID)
}

// GetChannelMeeting mocks base method.
func (m *MockStore) GetChannelMeeting(channelID string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelMeeting", channelID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetChannelMeeting indicates an expected call of GetChannelMeeting.
func (mr *MockStoreMockRecorder) GetChannelMeeting(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelMeeting", reflect.TypeOf((*MockStore)(nil).GetChannelMeeting), channelID)
}

// GetWebhookConfig mocks base method.
func (m *MockStore) GetWebhookConfig() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookConfig")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookConfig indicates an expected call of GetWebhookConfig.
func (mr *MockStoreMockRecorder) GetWebhookConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookConfig", reflect.TypeOf((*MockStore)(nil).GetWebhookConfig))
}

// RemoveCallParticipant mocks base method.
func (m *MockStore) RemoveCallParticipant(callID, userID string) ([]string, bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCallParticipant", callID, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// RemoveCallParticipant indicates an expected call of RemoveCallParticipant.
func (mr *MockStoreMockRecorder) RemoveCallParticipant(callID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCallParticipant", reflect.TypeOf((*MockStore)(nil).RemoveCallParticipant), callID, userID)
}

// SaveCall mocks base method.
func (m *MockStore) SaveCall(session *store.CallSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCall", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCall indicates an expected call of SaveCall.
func (mr *MockStoreMockRecorder) SaveCall(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCall", reflect.TypeOf((*MockStore)(nil).SaveCall), session)
}

// SaveChannelMeeting mocks base method.
func (m *MockStore) SaveChannelMeeting(channelID, meetingID, appConfigID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChannelMeeting", channelID, meetingID, appConfigID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveChannelMeeting indicates an expected call of SaveChannelMeeting.
func (mr *MockStoreMockRecorder) SaveChannelMeeting(channelID, meetingID, appConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChannelMeeting", reflect.TypeOf((*MockStore)(nil).SaveChannelMeeting), channelID, meetingID, appConfigID)
}

// StoreAppConfig mocks base method.
func (m *MockStore) StoreAppConfig(accountID, appID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAppConfig", accountID, appID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreAppConfig indicates an expected call of StoreAppConfig.
func (mr *MockStoreMockRecorder) StoreAppConfig(accountID, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAppConfig", reflect.TypeOf((*MockStore)(nil).StoreAppConfig), accountID, appID)
}

// StoreWebhookConfig mocks base method.
func (m *MockStore) StoreWebhookConfig(appConfigID, webhookID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWebhookConfig", appConfigID, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreWebhookConfig indicates an expected call of StoreWebhookConfig.
func (mr *MockStoreMockRecorder) StoreWebhookConfig(appConfigID, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWebhookConfig", reflect.TypeOf((*MockStore)(nil).StoreWebhookConfig), appConfigID, webhookID)
}

// UpdateCallSessionID mocks base method.
func (m *MockStore) UpdateCallSessionID(callID, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCallSessionID", callID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCallSessionID indicates an expected call of UpdateCallSessionID.
func (mr *MockStoreMockRecorder) UpdateCallSessionID(callID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCallSessionID", reflect.TypeOf((*MockStore)(nil).UpdateCallSessionID), callID, sessionID)
}

// UpsertCallsChannel mocks base method.
func (m *MockStore) UpsertCallsChannel(channel *store.CallsChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCallsChannel", channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCallsChannel indicates an expected call of UpsertCallsChannel.
func (mr *MockStoreMockRecorder) UpsertCallsChannel(channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCallsChannel", reflect.TypeOf((*MockStore)(nil).UpsertCallsChannel), channel)
}

// WithAppLock mocks base method.
func (m *MockStore) WithAppLock(ctx context.Context, key string, fn func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAppLock", ctx, key, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithAppLock indicates an expected call of WithAppLock.
func (mr *MockStoreMockRecorder) WithAppLock(ctx, key, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAppLock", reflect.TypeOf((*MockStore)(nil).WithAppLock), ctx, key, fn)
}
