// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kondo97/mattermost-plugin-rtk/server/store (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=server/store/mocks/mock_store.go -package=mocks github.com/kondo97/mattermost-plugin-rtk/server/store Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	store "github.com/kondo97/mattermost-plugin-rtk/server/store"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// EndCall mocks base method.
func (m *MockStore) EndCall(callID string, endAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndCall", callID, endAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndCall indicates an expected call of EndCall.
func (mr *MockStoreMockRecorder) EndCall(callID, endAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndCall", reflect.TypeOf((*MockStore)(nil).EndCall), callID, endAt)
}

// GetCallByChannel mocks base method.
func (m *MockStore) GetCallByChannel(channelID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByChannel", channelID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByChannel indicates an expected call of GetCallByChannel.
func (mr *MockStoreMockRecorder) GetCallByChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByChannel", reflect.TypeOf((*MockStore)(nil).GetCallByChannel), channelID)
}

// GetCallByID mocks base method.
func (m *MockStore) GetCallByID(callID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByID", callID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByID indicates an expected call of GetCallByID.
func (mr *MockStoreMockRecorder) GetCallByID(callID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByID", reflect.TypeOf((*MockStore)(nil).GetCallByID), callID)
}

// GetCallByMeetingID mocks base method.
func (m *MockStore) GetCallByMeetingID(meetingID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByMeetingID", meetingID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByMeetingID indicates an expected call of GetCallByMeetingID.
func (mr *MockStoreMockRecorder) GetCallByMeetingID(meetingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByMeetingID", reflect.TypeOf((*MockStore)(nil).GetCallByMeetingID), meetingID)
}

// GetWebhookID mocks base method.
func (m *MockStore) GetWebhookID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookID indicates an expected call of GetWebhookID.
func (mr *MockStoreMockRecorder) GetWebhookID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookID", reflect.TypeOf((*MockStore)(nil).GetWebhookID))
}

// GetWebhookSecret mocks base method.
func (m *MockStore) GetWebhookSecret() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookSecret")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookSecret indicates an expected call of GetWebhookSecret.
func (mr *MockStoreMockRecorder) GetWebhookSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookSecret", reflect.TypeOf((*MockStore)(nil).GetWebhookSecret))
}

// SaveCall mocks base method.
func (m *MockStore) SaveCall(session *store.CallSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCall", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCall indicates an expected call of SaveCall.
func (mr *MockStoreMockRecorder) SaveCall(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCall", reflect.TypeOf((*MockStore)(nil).SaveCall), session)
}

// StoreWebhookID mocks base method.
func (m *MockStore) StoreWebhookID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWebhookID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreWebhookID indicates an expected call of StoreWebhookID.
func (mr *MockStoreMockRecorder) StoreWebhookID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWebhookID", reflect.TypeOf((*MockStore)(nil).StoreWebhookID), id)
}

// StoreWebhookSecret mocks base method.
func (m *MockStore) StoreWebhookSecret(secret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWebhookSecret", secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreWebhookSecret indicates an expected call of StoreWebhookSecret.
func (mr *MockStoreMockRecorder) StoreWebhookSecret(secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWebhookSecret", reflect.TypeOf((*MockStore)(nil).StoreWebhookSecret), secret)
}

// UpdateCallParticipants mocks base method.
func (m *MockStore) UpdateCallParticipants(callID string, participants []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCallParticipants", callID, participants)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCallParticipants indicates an expected call of UpdateCallParticipants.
func (mr *MockStoreMockRecorder) UpdateCallParticipants(callID, participants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCallParticipants", reflect.TypeOf((*MockStore)(nil).UpdateCallParticipants), callID, participants)
}
