// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kondo97/mattermost-plugin-rtk/server/store (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=server/store/mocks/mock_store.go -package=mocks github.com/kondo97/mattermost-plugin-rtk/server/store Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	store "github.com/kondo97/mattermost-plugin-rtk/server/store"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClearWebhookConfig mocks base method.
func (m *MockStore) ClearWebhookConfig(appConfigID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearWebhookConfig", appConfigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearWebhookConfig indicates an expected call of ClearWebhookConfig.
func (mr *MockStoreMockRecorder) ClearWebhookConfig(appConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearWebhookConfig", reflect.TypeOf((*MockStore)(nil).ClearWebhookConfig), appConfigID)
}

// EndCall mocks base method.
func (m *MockStore) EndCall(callID string, endAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndCall", callID, endAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndCall indicates an expected call of EndCall.
func (mr *MockStoreMockRecorder) EndCall(callID, endAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndCall", reflect.TypeOf((*MockStore)(nil).EndCall), callID, endAt)
}

// GetAppID mocks base method.
func (m *MockStore) GetAppID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppID indicates an expected call of GetAppID.
func (mr *MockStoreMockRecorder) GetAppID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppID", reflect.TypeOf((*MockStore)(nil).GetAppID))
}

// GetCallByChannel mocks base method.
func (m *MockStore) GetCallByChannel(channelID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByChannel", channelID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByChannel indicates an expected call of GetCallByChannel.
func (mr *MockStoreMockRecorder) GetCallByChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByChannel", reflect.TypeOf((*MockStore)(nil).GetCallByChannel), channelID)
}

// GetCallByID mocks base method.
func (m *MockStore) GetCallByID(callID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByID", callID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByID indicates an expected call of GetCallByID.
func (mr *MockStoreMockRecorder) GetCallByID(callID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByID", reflect.TypeOf((*MockStore)(nil).GetCallByID), callID)
}

// GetCallByMeetingID mocks base method.
func (m *MockStore) GetCallByMeetingID(meetingID string) (*store.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByMeetingID", meetingID)
	ret0, _ := ret[0].(*store.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByMeetingID indicates an expected call of GetCallByMeetingID.
func (mr *MockStoreMockRecorder) GetCallByMeetingID(meetingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByMeetingID", reflect.TypeOf((*MockStore)(nil).GetCallByMeetingID), meetingID)
}

// GetChannelMeeting mocks base method.
func (m *MockStore) GetChannelMeeting(channelID string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelMeeting", channelID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetChannelMeeting indicates an expected call of GetChannelMeeting.
func (mr *MockStoreMockRecorder) GetChannelMeeting(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelMeeting", reflect.TypeOf((*MockStore)(nil).GetChannelMeeting), channelID)
}

// GetLatestAppConfigID mocks base method.
func (m *MockStore) GetLatestAppConfigID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAppConfigID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAppConfigID indicates an expected call of GetLatestAppConfigID.
func (mr *MockStoreMockRecorder) GetLatestAppConfigID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAppConfigID", reflect.TypeOf((*MockStore)(nil).GetLatestAppConfigID))
}

// GetWebhookConfig mocks base method.
func (m *MockStore) GetWebhookConfig() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookConfig")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookConfig indicates an expected call of GetWebhookConfig.
func (mr *MockStoreMockRecorder) GetWebhookConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookConfig", reflect.TypeOf((*MockStore)(nil).GetWebhookConfig))
}

// SaveCall mocks base method.
func (m *MockStore) SaveCall(session *store.CallSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCall", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCall indicates an expected call of SaveCall.
func (mr *MockStoreMockRecorder) SaveCall(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCall", reflect.TypeOf((*MockStore)(nil).SaveCall), session)
}

// SaveChannelMeeting mocks base method.
func (m *MockStore) SaveChannelMeeting(channelID, meetingID string, appConfigID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChannelMeeting", channelID, meetingID, appConfigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChannelMeeting indicates an expected call of SaveChannelMeeting.
func (mr *MockStoreMockRecorder) SaveChannelMeeting(channelID, meetingID, appConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChannelMeeting", reflect.TypeOf((*MockStore)(nil).SaveChannelMeeting), channelID, meetingID, appConfigID)
}

// StoreAppConfig mocks base method.
func (m *MockStore) StoreAppConfig(accountID, appID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAppConfig", accountID, appID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreAppConfig indicates an expected call of StoreAppConfig.
func (mr *MockStoreMockRecorder) StoreAppConfig(accountID, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAppConfig", reflect.TypeOf((*MockStore)(nil).StoreAppConfig), accountID, appID)
}

// StoreWebhookConfig mocks base method.
func (m *MockStore) StoreWebhookConfig(appConfigID string, webhookID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWebhookConfig", appConfigID, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreWebhookConfig indicates an expected call of StoreWebhookConfig.
func (mr *MockStoreMockRecorder) StoreWebhookConfig(appConfigID, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWebhookConfig", reflect.TypeOf((*MockStore)(nil).StoreWebhookConfig), appConfigID, webhookID)
}

// UpdateCallParticipants mocks base method.
func (m *MockStore) UpdateCallParticipants(callID string, participants []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCallParticipants", callID, participants)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCallParticipants indicates an expected call of UpdateCallParticipants.
func (mr *MockStoreMockRecorder) UpdateCallParticipants(callID, participants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCallParticipants", reflect.TypeOf((*MockStore)(nil).UpdateCallParticipants), callID, participants)
}
