// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kondo97/mattermost-plugin-rtk/server/store/kvstore (interfaces: KVStore)
//
// Generated by this command:
//
//	mockgen -destination=server/store/kvstore/mocks/mock_kvstore.go -package=mocks github.com/kondo97/mattermost-plugin-rtk/server/store/kvstore KVStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	kvstore "github.com/kondo97/mattermost-plugin-rtk/server/store/kvstore"
	gomock "go.uber.org/mock/gomock"
)

// MockKVStore is a mock of KVStore interface.
type MockKVStore struct {
	ctrl     *gomock.Controller
	recorder *MockKVStoreMockRecorder
	isgomock struct{}
}

// MockKVStoreMockRecorder is the mock recorder for MockKVStore.
type MockKVStoreMockRecorder struct {
	mock *MockKVStore
}

// NewMockKVStore creates a new mock instance.
func NewMockKVStore(ctrl *gomock.Controller) *MockKVStore {
	mock := &MockKVStore{ctrl: ctrl}
	mock.recorder = &MockKVStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKVStore) EXPECT() *MockKVStoreMockRecorder {
	return m.recorder
}

// EndCall mocks base method.
func (m *MockKVStore) EndCall(callID string, endAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndCall", callID, endAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndCall indicates an expected call of EndCall.
func (mr *MockKVStoreMockRecorder) EndCall(callID, endAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndCall", reflect.TypeOf((*MockKVStore)(nil).EndCall), callID, endAt)
}

// GetCallByChannel mocks base method.
func (m *MockKVStore) GetCallByChannel(channelID string) (*kvstore.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByChannel", channelID)
	ret0, _ := ret[0].(*kvstore.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByChannel indicates an expected call of GetCallByChannel.
func (mr *MockKVStoreMockRecorder) GetCallByChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByChannel", reflect.TypeOf((*MockKVStore)(nil).GetCallByChannel), channelID)
}

// GetCallByID mocks base method.
func (m *MockKVStore) GetCallByID(callID string) (*kvstore.CallSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallByID", callID)
	ret0, _ := ret[0].(*kvstore.CallSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallByID indicates an expected call of GetCallByID.
func (mr *MockKVStoreMockRecorder) GetCallByID(callID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallByID", reflect.TypeOf((*MockKVStore)(nil).GetCallByID), callID)
}

// GetTemplateData mocks base method.
func (m *MockKVStore) GetTemplateData(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateData", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateData indicates an expected call of GetTemplateData.
func (mr *MockKVStoreMockRecorder) GetTemplateData(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateData", reflect.TypeOf((*MockKVStore)(nil).GetTemplateData), userID)
}

// GetVoIPToken mocks base method.
func (m *MockKVStore) GetVoIPToken(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVoIPToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVoIPToken indicates an expected call of GetVoIPToken.
func (mr *MockKVStoreMockRecorder) GetVoIPToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVoIPToken", reflect.TypeOf((*MockKVStore)(nil).GetVoIPToken), userID)
}

// SaveCall mocks base method.
func (m *MockKVStore) SaveCall(session *kvstore.CallSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCall", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCall indicates an expected call of SaveCall.
func (mr *MockKVStoreMockRecorder) SaveCall(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCall", reflect.TypeOf((*MockKVStore)(nil).SaveCall), session)
}

// StoreVoIPToken mocks base method.
func (m *MockKVStore) StoreVoIPToken(userID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreVoIPToken", userID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreVoIPToken indicates an expected call of StoreVoIPToken.
func (mr *MockKVStoreMockRecorder) StoreVoIPToken(userID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreVoIPToken", reflect.TypeOf((*MockKVStore)(nil).StoreVoIPToken), userID, token)
}

// UpdateCallParticipants mocks base method.
func (m *MockKVStore) UpdateCallParticipants(callID string, participants []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCallParticipants", callID, participants)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCallParticipants indicates an expected call of UpdateCallParticipants.
func (mr *MockKVStoreMockRecorder) UpdateCallParticipants(callID, participants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCallParticipants", reflect.TypeOf((*MockKVStore)(nil).UpdateCallParticipants), callID, participants)
}
